apiVersion: v1
kind: Service
metadata:
  name: securechain-service
  namespace: securechain-dev
spec:
  type: NodePort
  selector:
    app: securechain-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080